# Generated by Django 2.2.6 on 2019-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_auto_20191117_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='id',
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
