# Generated by Django 2.2.6 on 2019-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_auto_20191121_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
