# Generated by Django 2.2.6 on 2019-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0006_auto_20191126_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reletionships',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='translate.Blog'),
        ),
    ]
