# Generated by Django 2.2.6 on 2019-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_auto_20191128_2347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
