# Generated by Django 2.2.6 on 2019-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0009_auto_20191208_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
