# Generated by Django 2.2.6 on 2019-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0010_auto_20191208_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
