# Generated by Django 2.2.6 on 2019-12-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0011_auto_20191208_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reletionships_with_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='with_heading', to='translate.Heading'),
        ),
    ]
