# Generated by Django 2.2.6 on 2019-12-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0012_auto_20191208_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reletionships_with_heading',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='with_heading', to='translate.Heading'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heading',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
