# Generated by Django 2.2.6 on 2019-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0013_auto_20191208_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
