# Generated by Django 2.2.6 on 2019-12-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0014_auto_20191215_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reletionships_with_heading',
        ),
    ]
