# Generated by Django 2.2.6 on 2020-01-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0016_auto_20191228_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitAuthBanIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('attempts', models.IntegerField(default=0, verbose_name='Неудачных попыток')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Время разблокировки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус блокировки')),
            ],
            options={
                'db_table': 'LimitAuthBanIp',
            },
        ),
    ]
