# Generated by Django 2.2.6 on 2020-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0018_bookmarkblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkblog',
            name='status_bookmark',
            field=models.BooleanField(default=False, verbose_name='Статус заметки'),
        ),
    ]
