# Generated by Django 2.2.6 on 2020-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0022_heading_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='translate/media/'),
        ),
    ]
