# Generated by Django 2.2.6 on 2020-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0023_auto_20200328_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
