# Generated by Django 2.2.6 on 2019-12-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='number_likes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
